eiffel-community/eiffelevents-sdk-dotnet

- dotnet.yml
This pull request closes the #3 issue.
The dotnet.yml file was added to build and run tests on each push or pull request on the Main branch.
To make sure that library build and tests run successfully.
permitted to submit under a different …
> Create build workflow (#3).

- README.md
- clients/README.md
This pull request resolves issue #1 for improving README files.
Enhance README files by updating the main repo README with 
- Add the SDK features and components.
- Add sample code. 
- Refine dependencies.
- Add README for example projects.
Make the repository more readable and easier to work with.
by …
> Enhance readme files

- .github/workflows/dotnet.yml
N/A
Update build workflow to run on development branch.
N/A
Ensure the SDK build and tests run on development branch.
N/A
(c) The contribution was provided directly to me …
> Update build workflow to run on development branch

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/ActivityCanceled.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- examples/EiffelClient.SubscriberTwo/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityCanceledEvent/EiffelActivityCanceledData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityCanceledEvent/EiffelActivityCanceledEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityCanceledEvent/EiffelActivityCanceledLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityCanceledEvent/EiffelActivityCanceledMeta.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelActivityExecutionLinks.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelActivityCanceledEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelActivityCanceledEventFixture.cs
This pull request resolves #22 for Add EiffelActivityCanceledEvent for Lyon edition.
- Implement EiffelActivityCanceledEvent for Lyon edition.
- Add EiffelActivityCanceledEvent tests.
- Add EiffelActivityCanceledEvent samples for Lyon edition.
by me, under the same open source …
> Lyon add eiffel activity canceled

- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelActivityExecutionLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelArtifact Link.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelBaseLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelCauseLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelChangeLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelCompositionLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelContextLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelDeresolvedIssueLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelElementLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelEnvironmentLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelFailedIssueLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelFlowContextLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelInconclusiveIssueLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelIutLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelModifiedAnnouncementLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelPartiallyResolvedIssueLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelPreviousActivityExecutionLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelPreviousVersionLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelResolvedIssueLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelReusedArtifactLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelRuntimeEnvironmentLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelSubConfidenceLevelLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelSubjectLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelSuccessfulIssueLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelTercLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelTestCaseExecutionLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelTestSuiteExecutionLink.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Links/EiffelVerificationBasisLink.cs
N/A
Add Lyon Link objects.
N/A
Link objects will be used in all new Lyon edition events.
N/A
person who …
> Lyon add links objects

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/ActivityStarted.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- examples/EiffelClient.SubscriberTwo/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityStartedEvent/EiffelActivityStartedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityStartedEvent/EiffelActivityStartedEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityStartedEvent/EiffelActivityStartedLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityStartedEvent/EiffelActivityStartedMeta.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Data/EiffelLiveLog.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelActivityStartedEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelActivityStartedEventFixture.cs
This pull request resolves #23 to add EiffelActivityStartedEvent for Lyon edition.
- Add EiffelActivityStartedEvent lyon edition.
- Add EiffelActivityStartedEvent lyon edition tests.
- Add EiffelActivityStartedEvent lyon edition samples.
N/A
by me, under the same open source …
> Lyon add eiffel activity started

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/ArtifactCreated.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- examples/EiffelClient.SubscriberTwo/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactCreatedEvent/EiffelArtifactCreatedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactCreatedEvent/EiffelArtifactCreatedEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactCreatedEvent/EiffelArtifactCreatedLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactCreatedEvent/EiffelArtifactCreatedMeta.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelArtifactCreatedEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelArtifactCreatedEventFixture.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Paris/EiffelArtifactCreatedEventFixture.cs
This pull request resolves #25 
- Add EiffelArtifactCreatedEvent Lyon edition.
- Add EiffelArtifactCreatedEvent Lyon edition tests
-  Add EiffelArtifactCreatedEvent Lyon edition samples.
N/A
N/A
permitted to submit under a …
> Lyon add eiffel artifact created

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/ArtifactPublished.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- examples/EiffelClient.SubscriberTwo/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactPublishedEvent/EiffelArtifactPublishedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactPublishedEvent/EiffelArtifactPublishedEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactPublishedEvent/EiffelArtifactPublishedLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelArtifactPublishedEvent/EiffelArtifactPublishedMeta.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelArtifactPublishedEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelArtifactPublishedEventFixture.cs
This pull request resolves #26 
- Add EiffelArtifactPublishedEvent Lyon edition.
- Add EiffelArtifactPublishedEvent Lyon edition tests.
- Add EiffelArtifactPublishedEvent Lyon edition examples.
N/A
N/A
permitted to submit …
> Lyon add artifact published

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/ActivityFinished.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- examples/EiffelClient.SubscriberTwo/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityFinishedEvent/EiffelActivityFinishedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityFinishedEvent/EiffelActivityFinishedEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityFinishedEvent/EiffelActivityFinishedLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelActivityFinishedEvent/EiffelActivityFinishedMeta.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/Shared/Data/EiffelPersistentLog.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelActivityFinishedEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelActivityFinishedEventFixture.cs
This PR resolves #24 
Add EiffelActivityFinishedEvent Lyon edition.
Add EiffelActivityFinishedEvent Lyon edition tests.
Add EiffelActivityFinishedEvent Lyon edition examples.
NA
NA
permitted to submit under a different …
> Lyon add activity finished

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/ConfidenceLevelModified.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- examples/EiffelClient.SubscriberTwo/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelConfidenceLevelModifiedEvent/EiffelConfidenceLevelModifiedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelConfidenceLevelModifiedEvent/EiffelConfidenceLevelModifiedEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelConfidenceLevelModifiedEvent/EiffelConfidenceLevelModifiedLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelConfidenceLevelModifiedEvent/EiffelConfidenceLevelModifiedMeta.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelConfidenceLevelModifiedEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelConfidenceLevelModifiedEventFixture.cs
This pull request resolves #28 
- Add EiffelConfidenceLevelModifiedEvent lyon edition.
- Add EiffelConfidenceLevelModifiedEvent tests.
- Add EiffelConfidenceLevelModifiedEvent Samples.
N/A
N/A
permitted to submit under a …
> Lyon add eiffel confidence level modified

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/CompositionDefined.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- examples/EiffelClient.SubscriberTwo/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelCompositionDefinedEvent/EiffelCompositionDefinedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelCompositionDefinedEvent/EiffelCompositionDefinedEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelCompositionDefinedEvent/EiffelCompositionDefinedLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelCompositionDefinedEvent/EiffelCompositionDefinedMeta.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelCompositionDefinedEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelCompositionDefinedEventFixture.cs
This PR closes #30 
- Add EiffelCompositionDefinedEvent lyon edition.
- Add EiffelCompositionDefinedEvent lyon edition tests.
- Add EiffelCompositionDefinedEvent lyon edition examples.
N/A
Support Lyon edition
N/A
permitted to submit under a …
> Lyon add add eiffel composition defined

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/EnvironmentDefined.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelEnvironmentDefinedEvent/EiffelEnvironmentDefinedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelEnvironmentDefinedEvent/EiffelEnvironmentDefinedEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelEnvironmentDefinedEvent/EiffelEnvironmentDefinedLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelEnvironmentDefinedEvent/EiffelEnvironmentDefinedMeta.cs
- src/EiffelEvents.Net/Events/Edition-Paris/EiffelEnvironmentDefinedEvent/EiffelEnvironmentDefinedData.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelEnvironmentDefinedEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelEnvironmentDefinedEventFixture.cs
This PR resolves #29.
Adding EiffelEnvironmentDefinedEvent
person who certified (a), …
> Lyon add environment defined

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/SourceChangeSubmitted.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- examples/EiffelClient.SubscriberTwo/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelSourceChangeSubmittedEvent/EiffelSourceChangeSubmittedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelSourceChangeSubmittedEvent/EiffelSourceChangeSubmittedEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelSourceChangeSubmittedEvent/EiffelSourceChangeSubmittedLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelSourceChangeSubmittedEvent/EiffelSourceChangeSubmittedMeta.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelSourceChangeSubmittedEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelSourceChangeSubmittedEventFixture.cs
This PR closes #32 
- Add EiffelSourceChangeSubmittedEvent lyon edition.
- Add EiffelSourceChangeSubmittedEvent lyon edition tests.
- Add EiffelSourceChangeSubmittedEvent lyon edition examples.
N/A
N/A
permitted to submit …
> Lyon add eiffel source change submitted

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/TestCaseTriggered.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- examples/EiffelClient.SubscriberTwo/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseTriggeredEvent/EiffelTestCaseTriggeredData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseTriggeredEvent/EiffelTestCaseTriggeredEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseTriggeredEvent/EiffelTestCaseTriggeredLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseTriggeredEvent/EiffelTestCaseTriggeredMeta.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelTestCaseTriggeredEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelTestCaseTriggeredEventFixture.cs
This PR closes #34 
- Add EiffelTestCaseTriggeredEvent Lyon edition.
- Add EiffelTestCaseTriggeredEvent Lyon edition tests.
- Add EiffelTestCaseTriggeredEvent Lyon edition. examples.
N/A
N/A
permitted to submit under a …
> Lyon add eiffel test case triggered

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/TestCaseCanceled.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseCanceledEvent/EiffelTestCaseCanceledData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseCanceledEvent/EiffelTestCaseCanceledEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseCanceledEvent/EiffelTestCaseCanceledLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseCanceledEvent/EiffelTestCaseCanceledMeta.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelTestCaseCanceledEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelTestCaseCanceledEventFixture.cs
This PR resolves #35 
- Add EiffelTestCaseCanceledEvent Lyon edition.
- Add EiffelTestCaseCanceledEvent Lyon edition test.
- Add EiffelTestCaseCanceledEvent Lyon edition examples.
N/A
N/A
permitted to submit under a different …
> Lyon add eiffel test case canceled

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/TestCaseFinished.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseFinishedEvent/EiffelTestCaseFinishedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseFinishedEvent/EiffelTestCaseFinishedEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseFinishedEvent/EiffelTestCaseFinishedLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseFinishedEvent/EiffelTestCaseFinishedMeta.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelTestCaseFinishedEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelTestCaseFinishedEventFixture.cs
This PR resolves #37.
- Add EiffelTestCaseFinishedEvent Lyon edition.
- Add EiffelTestCaseFinishedEvent Lyon edition test.
- Add EiffelTestCaseFinishedEvent Lyon edition examples.
permitted to submit under a different …
> Lyon add eiffel test case finished

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/TestSuiteFinished.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- examples/EiffelClient.SubscriberTwo/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestCaseFinishedEvent/EiffelTestCaseFinishedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestSuiteFinishedEvent/EiffelTestSuiteFinishedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestSuiteFinishedEvent/EiffelTestSuiteFinishedEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestSuiteFinishedEvent/EiffelTestSuiteFinishedLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelTestSuiteFinishedEvent/EiffelTestSuiteFinishedMeta.cs
- src/EiffelEvents.Net/Events/Edition-Paris/Shared/Data/EiffelTestCaseOutcome.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelTestSuiteFinishedEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelTestSuiteFinishedEventFixture.cs
This PR closes #39 
- Fix EiffelOutcome namespace.
- Add EiffelTestSuiteFinishedEvent Lyon edition.
- Add EiffelTestSuiteFinishedEvent Lyon edition tests.
- Add EiffelTestSuiteFinishedEvent Lyon edition examples.
N/A
N/A …
> Lyon add eiffel test suite finished

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/IssueVerified.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- examples/EiffelClient.SubscriberTwo/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelIssueVerifiedEvent/EiffelIssueVerifiedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelIssueVerifiedEvent/EiffelIssueVerifiedEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelIssueVerifiedEvent/EiffelIssueVerifiedLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelIssueVerifiedEvent/EiffelIssueVerifiedMeta.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelIssueVerifiedEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelIssueVerifiedEventFixture.cs
This PR closes #40 
- Add EiffelIssueVerifiedEvent Lyon edition.
- Add EiffelIssueVerifiedEvent Lyon edition tests.
- Add EiffelIssueVerifiedEvent Lyon edition examples.
N/A
Support Lyon edition
N/A
permitted to submit under a different license), …
> Lyon add eiffel issue verified

- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/AnnouncementPublished.cs
- examples/EiffelClient.PublisherOne/Models/Edition-Lyon/Client.cs
- examples/EiffelClient.PublisherOne/Program.cs
- examples/EiffelClient.SubscriberOne/Program.cs
- examples/EiffelClient.SubscriberTwo/Program.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelAnnouncementPublishedEvent/EiffelAnnouncementPublishedData.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelAnnouncementPublishedEvent/EiffelAnnouncementPublishedEvent.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelAnnouncementPublishedEvent/EiffelAnnouncementPublishedLinks.cs
- src/EiffelEvents.Net/Events/Edition-Lyon/EiffelAnnouncementPublishedEvent/EiffelAnnouncementPublishedMeta.cs
- tests/EiffelEvents.Net.Tests/Events/Edition-Lyon/EiffelAnnouncementPublishedEventTests.cs
- tests/EiffelEvents.Net.Tests/TestData/Edition-Lyon/EiffelAnnouncementPublishedEventFixture.cs
This PR closes #43
- Add EiffelAnnouncementPublishedEvent Lyon edition.
- Add EiffelAnnouncementPublishedEvent Lyon edition tests.
- Add EiffelAnnouncementPublishedEvent Lyon edition examples.
N/A
N/A
permitted to submit …
> Lyon add eiffel announcement published

- src/EiffelEvents.Clients.RabbitMq/EiffelEvents.Clients.RabbitMq.csproj
- src/EiffelEvents.Clients.RabbitMq/EiffelEvents.Clients.RabbitMq.nuspec
- src/EiffelEvents.Net/EiffelEvents.Net.csproj
- src/EiffelEvents.Net/EiffelEvents.Net.nuspec
- tests/EiffelEvents.Net.Tests/Helpers/VersionHelper.cs
This PR resolves #82 
Upgrade dependencies to latest versions
person who certified (a), (b) or (c) and I …
> upgrade dependencies - upgrade library versions

- src/EiffelEvents.Clients.RabbitMq/EiffelEvents.Clients.RabbitMq.csproj
- src/EiffelEvents.Clients.RabbitMq/EiffelEvents.Clients.RabbitMq.nuspec
- src/EiffelEvents.Net/EiffelEvents.Net.csproj
- src/EiffelEvents.Net/EiffelEvents.Net.nuspec
- tests/EiffelEvents.Net.Tests/Helpers/VersionHelper.cs
* upgrade dependencies - upgrade library versions
upgrade dependencies - upgrade library versions
person …
> upgrade dependencies - upgrade library versions (#83)

- src/EiffelEvents.Clients.RabbitMq/EiffelEvents.Clients.RabbitMq.csproj
- src/EiffelEvents.Clients.RabbitMq/EiffelEvents.Clients.RabbitMq.nuspec
- src/EiffelEvents.Net/EiffelEvents.Net.csproj
- src/EiffelEvents.Net/EiffelEvents.Net.nuspec
- tests/EiffelEvents.Net.Tests/Helpers/VersionHelper.cs
NA
Prepare the package for version 1.0.3
person who certified (a), (b) or (c) and I have not modified
it. …
> update package version to 1.0.3 and changes
